### ISSUE TITLE
TimeFormat! or WaitTime

### ISSUE THREAD

**Issue by galaxytwenty** [ColinHDev/CSkull#3]
Hey **ColinHDev**,
Can u Change the **TimeFormat** or an **Extra option** to display wait time like
you have to wait **7days 2hours 23minutes 14seconds**

Reason is, when you make it, in german we can say 1Tag 2Stunden 23Minuten 14Sekunden

The time **goes not down** when i try to run this command again
it says multiple of time the same rest wait time.

Thank in advance
**GLX20**

**Comment by ColinHDev** [comment]
Hey,
I understand your suggestion, but the reason I didn't use it was because the time format you are proposing is a pain to develop.
One problem is the singular and plural forms of those terms: 2 day**s** but 1 day (or 2 Tag**e** but 1 Tag in german). 
Another one is if a unit is zero. Nobody would want their message to look like: `You can claim another skull again in 0 days, 0 hours, 0 minutes and 5 seconds.`
Although both problems can be fixed, it is not easily or for users understandably possible with the current language file design.

**Comment by galaxytwenty** [comment]
Okay, allright... can u Update Cskull to PM5 ?
